### ISSUE TITLE
When viral mobs appeared, they must have NAN health

### ISSUE THREAD

**Issue by rebarakuk** [Wurmatron/Viral#10]
and it can't be fixed by Entity NAN health fix or NANpolice

maybe it had a conflict with other mods

**Comment by Wurmatron** [comment]
Is it mob considered a monster? Or passive?
Does it normally or by other mods spawn with 1 HP or 1/2 heart? 

1. If it's a monster and spawning with low HP,  it's NaN HP is a bug. 
2. If it's "passive" it's very likely a mod issue / conflict.

The first option will be fixable by me, however HP fixer mods are unlikely to fix it, due to how it's been written.

The second option is some form of conflict requiring testing.

**Comment by rebarakuk** [comment]
It's a monster.
when an entity gets the virus, its health get higher and higher.
If there's no other mod, the health stops to 1024, but with other mods, its health grow for a few seconds and finally becomes NaN health.

**Comment by Wurmatron** [comment]
Yep, that is definitely a bug, I'll try fixing it later this week when I get some time.

**Comment by Wurmatron** [comment]
Should be fixed now, I did little testing however I added 2 possible fixes,
1. HP overflow detection and prevention, 1 below max int / overflow
2. Added 'maxHPGrowth' config option to allow for fine-tuning of infected mobs max hp

Note: I should also have fixed the hp growth bug (per tick), it should stay the same after being infected.

**Comment by Wurmatron** [comment]
https://www.curseforge.com/minecraft/mc-mods/viral/files/3642621
